name = "Test"
toggle = true

[[scripts]]
name = "basic_script"
inline = """
if toggle then
    print("Toggle is true")
else
    print("Toggle is false")
end
"""

[[scripts]]
name = "self_mutating"
path = "./examples/self_mutating.lua"

[[scripts]]
name = "faulty"
inline = """
if toggle then
    print("Toggle is true")
else
    print("Toggle is false")
"""
